let templates = {
  搜索模板: [
    {
      搜索数组: 'module-search-item">&&<div+1',
      搜索标题: '<a class="video-serial"*alt="&&">',
      搜索副标题: '<a class="video-serial"*>&&</a',
      搜索链接: '<a class="video-serial"*href="&&"',
    },
  ],
};

let autoRule = {
  数组: [
    'hl-list-item&&</li>',
    'myui-vodlist__box&&</div',
    'class="stui-vodlist__box"&&</a',
    '<a&&</a>[包含:module-item-cover#vodlist_thumb]',
    'oneVideo">&&<div class="col',
    '"video-img-box&&</p',
    '<article&&</article>',
    '<li class="clearfix">&&</li>',
    'module-item"&&</div+1[不包含:module-item-ru]',
    'module-search-item">&&<div+1',
    '<a&&</a>',
  ],
  图片: ['data-src="&&"', 'original="&&"', '<img*src="&&"'],
  标题: ['alt="&&"', 'title="&&"', 'name">&&<'],
  链接: ['href="&&"', "href='&&'"],
  副标题: [
    'module-item-text">&&<',
    '"v_note">&&</div',
    'class="pic-text*text-right">&&<',
    '"v-ins"><p>&&</p>',
    'module-item-note">&&<',
    'class="*remarks"&&<',
    'v-item-bottom">&&</span>',
    'class="pic_text*">&&<',
    '<span class="qb">&&</span>',
    '<span*>&&</span>',
    '<span>&&</span>',
  ],
  线路数组: [
    'module-tab-item &&</small>',
    'module-tab-item&&</div>',
    'module-tab-item &&</a>',
    'tabindex=*"tab">&&<',
    '"tab"*>&&<[不包含:同]',
    '"hl-text-site">&&<[不包含:评分#微信#扫一扫]',
    'playfrom*>&&</div>',
    'channelname*>&&</a>',
    'tabs-play*>&&</span>',
    '="pull-left"*>&&<',
    'pay-url*>&&</a>',
    'myui-panel__head&&</h3>[包含:fa-sort][替换:排序>>]',
    '<a&&</a>[包含:class="wo"]',
    'href="javascript:void(0);&&</a>[包含:alt]',
    '"radius1*>&&</a>',
    'href="javascript:void(0);"&&</a>',
    '"stui-pannel__head*span>&&</div>[包含:线路]',
    'id="playlist">&&</div>',
    '<h3*>&&</h3>[不包含:正片#猜#热#熱#更#介#榜#情#链#表#荐#排#评#留言#讨论#记#同#最新#演#正在#href=#收藏#明星#分享#相关#]',
    '<h4*>&&</h4>[不包含:正片#猜#热#熱#更#介#榜#情#链#表#荐#排#评#留言#讨论#记#同#最新#演#正在#href=#收藏#明星#分享#相关#]',
    '<h2*>&&</h2>[不包含:正片#猜#热#熱#更#介#榜#情#链#表#排#评#留言#讨论#记#同#最新#演#正在#href=#收藏#明星#分享#相关]',
  ],
  线路标题: [
    '换线路&&</ul>',
    '选择播放源&&</ul>',
    '节点列表&&</ul>',
    '<ul*tab-title"&&</ul>',
    '<ul class="nav nav-btn&&</ul>[不包含:首页#电影]',
    '"playname"&&</ul>',
    'from*list"&&</ul>',
    '<dt&&</dt>',
    'play_source_tab&&</div>',
    'data-dropdown-value="&&">',
    'alt="&&"',
  ],
  播放数组: [
    'hl-sort-list&&</ul>',
    'sort-list clearfix&&</ul>',
    'id="hl-plays-list&&</ul>',
    'id="con_playlist&&</ul>',
    '<ul class="stui-play*list&&</ul>',
    '<ul class="myui-play*list&&</ul>',
    '<ul class="stui-content*playlist&&</ul>',
    '<ul class="content*playlist clearfix"&&</ul>',
    '<div class="stui-content*playlist&&</div>',
    '<ul class="myui-content*list&&</ul>',
    '<ul id="playsx"&&</ul>',
    '<div class="module-play-list&&</div>',
    '<ul class="play_list"&&</ul>',
    '<ul class="large_list&&</ul>',
    '"tab_con"&&</ul>',
    '<ul class="playlist&&</ul>',
    'class="scroll-content&&</div></div>',
    '<ul class="anthology-list-play&&</ul',
  ],
  播放列表: '<a&&</a>[不包含:src=#original=#background#tab-item#节点#线路#福利#推荐#追剧#游客#留言#求片#影视#下载]',
  播放标题: [
    'span>&&<',
    'title="&&"',
    '>&&</a>[包含:集#清#版#HD#BD#0P#原画#蓝光#字#正片#0p#TC#TS#DVD#CD#期#季#语#话#1#2#3#4#5#6#7#8#9#]',
  ],
  播放链接:
    'href="&&"[不包含:href="/"#search#show#view#detail#juqing#type#script#Script#read#list#/hot/#index.html#/news/#email#/appxz/#/tags/#.xml#.js#url=http#.app]',
  简介: ['name="description"*content="&&"', '剧情&&</p>[不包含:首页]'],
  影片状态: '状态：&&</div>',
  影片类型: '类型：&&</div>',
  影片地区: '地区：&&</div>',
  主演: ['主演：&&</div>', '演员:&&</div>'],
  导演: ['导演：&&</div>', '导演:&&</div>'],
  剧情: '电影--喜剧&爱情&动作&科幻&剧情&战争&警匪&犯罪&动画&奇幻&武侠&冒险&枪战&恐怖&悬疑&青春&古装&历史&运动&儿童||连续剧--古装&神话&战争&偶像&爱情&喜剧&家庭&犯罪&悬疑&恐怖&武侠&动作&奇幻&剧情&历史||综艺--脱口秀&真人秀&情感&旅游&音乐&舞蹈&美食&纪实&生活||动漫--科幻&热血&搞笑&冒险&校园&动作&运动||纪录片--纪录&历史&传记&音乐&歌舞&短片&科幻',
  地区: '电影--大陆&香港&台湾&美国&法国&英国&日本&韩国&德国&泰国&印度&俄罗斯&意大利&西班牙&加拿大||连续剧--大陆&香港&台湾&美国&法国&英国&日本&韩国&德国&泰国&印度&俄罗斯&意大利&西班牙&加拿大||综艺--大陆&香港&台湾&日本&韩国&美国&英国||动漫--大陆&日本&韩国&美国&英国&法国||纪录片--大陆&香港&台湾&美国&法国&英国&日本&韩国&德国&泰国&印度&俄罗斯&意大利&西班牙&加拿大',
  排序: '时间$time#人气$hits#评分$score',
  年份: '',
};

let extRule = {
  搜索: ['<form name="search"*action="&&"', '<form id="search"*action="&&"'],
};

let searchmap = new Map([
  ['/ss/-------------/', '/ss/{wd}----------{pg}---/'],
  ['/vsearch/-------------.html', '/vsearch/{wd}----------{pg}---.html'],
  ['/vodsearch/-------------.html', '/vodsearch/{wd}----------{pg}---.html'],
  ['/index.php/vod/search.html', '/index.php/vod/search/page/{pg}/wd/{wd}.html'],
]);

export { templates, autoRule, extRule, searchmap };
