/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const TAB_AND_NEW_LINE: typeof import('tdesign-vue-next')['AB_AND_NEW_LINE']
  const TEA_ID: typeof import('tdesign-vue-next')['EA_ID']
  const TEMPLATE: typeof import('tdesign-vue-next')['EMPLATE']
  const TIAS: typeof import('tdesign-vue-next')['IAS']
  const TIME_REGEX_LIST: typeof import('tdesign-vue-next')['IME_REGEX_LIST']
  const TIME_UPDATE: typeof import('tdesign-vue-next')['IME_UPDATE']
  const TOB_URL: typeof import('tdesign-vue-next')['OB_URL']
  const TOUCHS: typeof import('tdesign-vue-next')['OUCHS']
  const TO_LOCALE_STRING_BUG: typeof import('tdesign-vue-next')['O_LOCALE_STRING_BUG']
  const TO_OBJECT_BUG: typeof import('tdesign-vue-next')['O_OBJECT_BUG']
  const TO_PRIMITIVE: typeof import('tdesign-vue-next')['O_PRIMITIVE']
  const TO_STRING: typeof import('tdesign-vue-next')['O_STRING']
  const TO_STRING$1: typeof import('tdesign-vue-next')['O_STRING$1']
  const TO_STRING_TAG: typeof import('tdesign-vue-next')['O_STRING_TAG']
  const TO_STRING_TAG$1: typeof import('tdesign-vue-next')['O_STRING_TAG$1']
  const TO_STRING_TAG$2: typeof import('tdesign-vue-next')['O_STRING_TAG$2']
  const TO_STRING_TAG$3: typeof import('tdesign-vue-next')['O_STRING_TAG$3']
  const TO_STRING_TAG$4: typeof import('tdesign-vue-next')['O_STRING_TAG$4']
  const TO_STRING_TAG_SUPPORT: typeof import('tdesign-vue-next')['O_STRING_TAG_SUPPORT']
  const TO_STRING_TAG_SUPPORT$1: typeof import('tdesign-vue-next')['O_STRING_TAG_SUPPORT$1']
  const TO_STRING_TAG_SUPPORT$2: typeof import('tdesign-vue-next')['O_STRING_TAG_SUPPORT$2']
  const TYPED_ARRAYS_CONSTRUCTORS_REQUIRES_WRAPPERS: typeof import('tdesign-vue-next')['YPED_ARRAYS_CONSTRUCTORS_REQUIRES_WRAPPERS']
  const TYPED_ARRAY_CONSTRUCTOR: typeof import('tdesign-vue-next')['YPED_ARRAY_CONSTRUCTOR']
  const TYPED_ARRAY_TAG: typeof import('tdesign-vue-next')['YPED_ARRAY_TAG']
  const TYPED_ARRAY_TAG$1: typeof import('tdesign-vue-next')['YPED_ARRAY_TAG$1']
  const TYPED_ARRAY_TAG_REQUIRED: typeof import('tdesign-vue-next')['YPED_ARRAY_TAG_REQUIRED']
}
