export default {
  title: 'Intelligent Assistant',
  subheading: 'AIGC',
  field: {
    key: 'Key',
    model: 'Model',
    providerMap: {
      amazon: 'Amazon Bedrock',
      anthropic: 'Anthropic',
      azure: 'Azure',
      gemini: 'Gemini',
      openai: 'OpenAI',
    },
  },
  chat: {
    tip: 'Hello! I am the {0} intelligent assistant, how can I help you?',
    suggestion: {
      desc: {
        title: 'What is {0}?',
        prompt: 'Introduce {0}',
      },
    },
    modelChange: 'Provided by {0} model',
    stopGenerating: 'User has stopped content generation',
  },
  status: {
    reason: 'Think',
    reasoning: 'Thinking...',
    reasoned: 'Thought deeply',
  },
  declare: 'Content generated by AI, for reference only.',
  noParam: 'Parameters are incorrect, please go to [Setting->Base Config] to configure ai related data.',
  message: {
    createSessionFailed: 'Create session failed',
  },
};
