/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const DialogPlugin: typeof import('tdesign-vue-next')['DialogPlugin']
  const MessagePlugin: typeof import('tdesign-vue-next')['MessagePlugin']
  const TBSCertificate: typeof import('tdesign-vue-next')['BSCertificate']
  const TCPlayer: typeof import('tdesign-vue-next')['CPlayer']
  const TDesign: typeof import('tdesign-vue-next')['Design']
  const TDesignChat: typeof import('tdesign-vue-next')['DesignChat']
  const TEN: typeof import('tdesign-vue-next')['EN']
  const THREE: typeof import('tdesign-vue-next')['HREE']
  const TICKING: typeof import('tdesign-vue-next')['ICKING']
  const TIMEOUT: typeof import('tdesign-vue-next')['IMEOUT']
  const TWENTYFOUR: typeof import('tdesign-vue-next')['WENTYFOUR']
  const TWO: typeof import('tdesign-vue-next')['WO']
}
