/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const MessagePlugin: typeof import('tdesign-vue-next')['MessagePlugin']
  const TCPlayer: typeof import('tdesign-vue-next')['CPlayer']
}
