/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue';

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Ai: typeof import('./src/components/quick-menu/components/Ai.vue')['default']
    Aigc: typeof import('./src/components/aigc/index.vue')['default']
    CommonNav: typeof import('./src/components/common-nav/index.vue')['default']
    DialogDocment: typeof import('./src/components/dialog-docment/index.vue')['default']
    GroupBtn: typeof import('./src/components/group-btn/index.vue')['default']
    HelpAction: typeof import('./src/components/action/components/HelpAction.vue')['default']
    Index_bot: typeof import('./src/components/aigc/index_bot.vue')['default']
    Index_old: typeof import('./src/components/aigc/index_old.vue')['default']
    InputAction: typeof import('./src/components/action/components/InputAction.vue')['default']
    InputReq: typeof import('./src/components/input-req/index.vue')['default']
    InputShortcut: typeof import('./src/components/input-shortcut/index.vue')['default']
    Lab: typeof import('./src/components/quick-menu/components/Lab.vue')['default']
    Language: typeof import('./src/components/quick-menu/components/Language.vue')['default']
    LazyBg: typeof import('./src/components/lazy-bg/index.vue')['default']
    MenuAction: typeof import('./src/components/action/components/MenuAction.vue')['default']
    MsgBoxAction: typeof import('./src/components/action/components/MsgBoxAction.vue')['default']
    MultiInputAction: typeof import('./src/components/action/components/MultiInputAction.vue')['default']
    PlayShow: typeof import('./src/components/play-show/index.vue')['default']
    QuickMenu: typeof import('./src/components/quick-menu/index.vue')['default']
    RenderIcon: typeof import('./src/components/render-icon/index.vue')['default']
    RenderMarkdown: typeof import('./src/components/render-markdown/index.vue')['default']
    RouterControl: typeof import('./src/components/router-control/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPanel: typeof import('./src/components/search-panel/index.vue')['default']
    Setting: typeof import('./src/components/quick-menu/components/Setting.vue')['default']
    SettingTable: typeof import('./src/components/setting-table/index.vue')['default']
    Share: typeof import('./src/components/share/index.vue')['default']
    Sponsor: typeof import('./src/components/quick-menu/components/Sponsor.vue')['default']
    SystemControl: typeof import('./src/components/system-control/index.vue')['default']
    TagNav: typeof import('./src/components/tag-nav/index.vue')['default']
    TAside: typeof import('tdesign-vue-next')['Aside']
    TBackTop: typeof import('tdesign-vue-next')['BackTop']
    TBreadcrumb: typeof import('tdesign-vue-next')['Breadcrumb']
    TBreadcrumbItem: typeof import('tdesign-vue-next')['BreadcrumbItem']
    TButton: typeof import('tdesign-vue-next')['Button']
    TChatActionbar: typeof import('@tdesign-vue-next/chat')['ChatActionbar']
    TChatList: typeof import('@tdesign-vue-next/chat')['ChatList']
    TChatMarkdown: typeof import('@tdesign-vue-next/chat')['ChatMarkdown']
    TChatMessage: typeof import('@tdesign-vue-next/chat')['ChatMessage']
    TChatSender: typeof import('@tdesign-vue-next/chat')['ChatSender']
    TCol: typeof import('tdesign-vue-next')['Col']
    TConfigProvider: typeof import('tdesign-vue-next')['ConfigProvider']
    TContent: typeof import('tdesign-vue-next')['Content']
    TDialog: typeof import('tdesign-vue-next')['Dialog']
    TDrawer: typeof import('tdesign-vue-next')['Drawer']
    TDropdown: typeof import('tdesign-vue-next')['Dropdown']
    TDropdownItem: typeof import('tdesign-vue-next')['DropdownItem']
    TDropdownMenu: typeof import('tdesign-vue-next')['DropdownMenu']
    TEmpty: typeof import('tdesign-vue-next')['Empty']
    Terminal: typeof import('./src/components/terminal/index.vue')['default']
    THeader: typeof import('tdesign-vue-next')['Header']
    Theme: typeof import('./src/components/quick-menu/components/Theme.vue')['default']
    TImage: typeof import('tdesign-vue-next')['Image']
    TInput: typeof import('tdesign-vue-next')['Input']
    TInputNumber: typeof import('tdesign-vue-next')['InputNumber']
    TitleMenu: typeof import('./src/components/title-menu/index.vue')['default']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TList: typeof import('tdesign-vue-next')['List']
    TListItem: typeof import('tdesign-vue-next')['ListItem']
    TLoading: typeof import('tdesign-vue-next')['Loading']
    TMenu: typeof import('tdesign-vue-next')['Menu']
    TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
    TOption: typeof import('tdesign-vue-next')['Option']
    TPopup: typeof import('tdesign-vue-next')['Popup']
    TRadioButton: typeof import('tdesign-vue-next')['RadioButton']
    TRadioGroup: typeof import('tdesign-vue-next')['RadioGroup']
    TRow: typeof import('tdesign-vue-next')['Row']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TSkeleton: typeof import('tdesign-vue-next')['Skeleton']
    TSpace: typeof import('tdesign-vue-next')['Space']
    TTabPanel: typeof import('tdesign-vue-next')['TabPanel']
    TTabs: typeof import('tdesign-vue-next')['Tabs']
    TTooltip: typeof import('tdesign-vue-next')['Tooltip']
    Webview: typeof import('./src/components/webview/index.vue')['default']
  }
}

// For TSX support
declare global {
  const Ai: (typeof import('./src/components/quick-menu/components/Ai.vue'))['default'];
  const Aigc: (typeof import('./src/components/aigc/index.vue'))['default'];
  const CommonNav: (typeof import('./src/components/common-nav/index.vue'))['default'];
  const DialogDocment: (typeof import('./src/components/dialog-docment/index.vue'))['default'];
  const GroupBtn: (typeof import('./src/components/group-btn/index.vue'))['default'];
  const HelpAction: (typeof import('./src/components/action/components/HelpAction.vue'))['default'];
  const Index_bot: (typeof import('./src/components/aigc/index_bot.vue'))['default'];
  const Index_old: (typeof import('./src/components/aigc/index_old.vue'))['default'];
  const InputAction: (typeof import('./src/components/action/components/InputAction.vue'))['default'];
  const InputReq: (typeof import('./src/components/input-req/index.vue'))['default'];
  const InputShortcut: (typeof import('./src/components/input-shortcut/index.vue'))['default'];
  const Lab: (typeof import('./src/components/quick-menu/components/Lab.vue'))['default'];
  const Language: (typeof import('./src/components/quick-menu/components/Language.vue'))['default'];
  const LazyBg: (typeof import('./src/components/lazy-bg/index.vue'))['default'];
  const MenuAction: (typeof import('./src/components/action/components/MenuAction.vue'))['default'];
  const MsgBoxAction: (typeof import('./src/components/action/components/MsgBoxAction.vue'))['default'];
  const MultiInputAction: (typeof import('./src/components/action/components/MultiInputAction.vue'))['default'];
  const PlayShow: (typeof import('./src/components/play-show/index.vue'))['default'];
  const QuickMenu: (typeof import('./src/components/quick-menu/index.vue'))['default'];
  const RenderIcon: (typeof import('./src/components/render-icon/index.vue'))['default'];
  const RenderMarkdown: (typeof import('./src/components/render-markdown/index.vue'))['default'];
  const RouterControl: (typeof import('./src/components/router-control/index.vue'))['default'];
  const RouterLink: (typeof import('vue-router'))['RouterLink'];
  const RouterView: (typeof import('vue-router'))['RouterView'];
  const SearchPanel: (typeof import('./src/components/search-panel/index.vue'))['default'];
  const Setting: (typeof import('./src/components/quick-menu/components/Setting.vue'))['default'];
  const SettingTable: (typeof import('./src/components/setting-table/index.vue'))['default'];
  const Share: (typeof import('./src/components/share/index.vue'))['default'];
  const Sponsor: (typeof import('./src/components/quick-menu/components/Sponsor.vue'))['default'];
  const SystemControl: (typeof import('./src/components/system-control/index.vue'))['default'];
  const TagNav: (typeof import('./src/components/tag-nav/index.vue'))['default'];
  const TAside: (typeof import('tdesign-vue-next'))['Aside'];
  const TBackTop: (typeof import('tdesign-vue-next'))['BackTop'];
  const TBreadcrumb: (typeof import('tdesign-vue-next'))['Breadcrumb'];
  const TBreadcrumbItem: (typeof import('tdesign-vue-next'))['BreadcrumbItem'];
  const TButton: (typeof import('tdesign-vue-next'))['Button'];
  const TChatActionbar: (typeof import('@tdesign-vue-next/chat'))['ChatActionbar'];
  const TChatList: (typeof import('@tdesign-vue-next/chat'))['ChatList'];
  const TChatMarkdown: (typeof import('@tdesign-vue-next/chat'))['ChatMarkdown'];
  const TChatMessage: (typeof import('@tdesign-vue-next/chat'))['ChatMessage'];
  const TChatSender: (typeof import('@tdesign-vue-next/chat'))['ChatSender'];
  const TCol: (typeof import('tdesign-vue-next'))['Col'];
  const TConfigProvider: (typeof import('tdesign-vue-next'))['ConfigProvider'];
  const TContent: (typeof import('tdesign-vue-next'))['Content'];
  const TDialog: (typeof import('tdesign-vue-next'))['Dialog'];
  const TDrawer: (typeof import('tdesign-vue-next'))['Drawer'];
  const TDropdown: (typeof import('tdesign-vue-next'))['Dropdown'];
  const TDropdownItem: (typeof import('tdesign-vue-next'))['DropdownItem'];
  const TDropdownMenu: (typeof import('tdesign-vue-next'))['DropdownMenu'];
  const TEmpty: (typeof import('tdesign-vue-next'))['Empty'];
  const Terminal: (typeof import('./src/components/terminal/index.vue'))['default'];
  const THeader: (typeof import('tdesign-vue-next'))['Header'];
  const Theme: (typeof import('./src/components/quick-menu/components/Theme.vue'))['default'];
  const TImage: (typeof import('tdesign-vue-next'))['Image'];
  const TInput: (typeof import('tdesign-vue-next'))['Input'];
  const TInputNumber: (typeof import('tdesign-vue-next'))['InputNumber'];
  const TitleMenu: (typeof import('./src/components/title-menu/index.vue'))['default'];
  const TLayout: (typeof import('tdesign-vue-next'))['Layout'];
  const TList: (typeof import('tdesign-vue-next'))['List'];
  const TListItem: (typeof import('tdesign-vue-next'))['ListItem'];
  const TLoading: (typeof import('tdesign-vue-next'))['Loading'];
  const TMenu: (typeof import('tdesign-vue-next'))['Menu'];
  const TMenuItem: (typeof import('tdesign-vue-next'))['MenuItem'];
  const TOption: (typeof import('tdesign-vue-next'))['Option'];
  const TPopup: (typeof import('tdesign-vue-next'))['Popup'];
  const TRadioButton: (typeof import('tdesign-vue-next'))['RadioButton'];
  const TRadioGroup: (typeof import('tdesign-vue-next'))['RadioGroup'];
  const TRow: (typeof import('tdesign-vue-next'))['Row'];
  const TSelect: (typeof import('tdesign-vue-next'))['Select'];
  const TSkeleton: (typeof import('tdesign-vue-next'))['Skeleton'];
  const TSpace: (typeof import('tdesign-vue-next'))['Space'];
  const TTabPanel: (typeof import('tdesign-vue-next'))['TabPanel'];
  const TTabs: (typeof import('tdesign-vue-next'))['Tabs'];
  const TTooltip: (typeof import('tdesign-vue-next'))['Tooltip'];
  const Webview: (typeof import('./src/components/webview/index.vue'))['default'];
}
